source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'LycamPlusIMSDK-iOS_Example', :exclusive => true do
  pod "LycamPlusIMSDK", :path => "../"
end

target 'LycamPlusIMSDK-iOS_Tests', :exclusive => true do
  pod "LycamPlusIMSDK", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
